# Generated by Django 2.1.7 on 2019-04-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_auto_20190401_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='model_pic',
            field=models.ImageField(default=1, upload_to='foto-funcionario/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
