# Generated by Django 2.1.7 on 2019-04-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_auto_20190401_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='model_pic',
            new_name='imagem',
        ),
    ]
