# Generated by Django 2.1.7 on 2019-04-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_auto_20190401_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='aniversarop',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='regiao',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
