# Generated by Django 2.1.7 on 2019-04-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_auto_20190401_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='aniversarop',
            new_name='aniversario',
        ),
    ]
