# Generated by Django 2.1.7 on 2019-04-12 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0008_auto_20190410_1633'),
        ('aluno', '0001_initial'),
        ('empresas', '0003_auto_20190412_1625'),
        ('financeiro', '0002_mensalidades_status_mensalidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidades',
            name='aluno',
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='datadaparcela',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='matriculaid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.Matricula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='nomeAluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='aluno.Aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='parcelamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parcelamento'),
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='parcelaqualdequal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parcela qual de qual'),
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='totalapagar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total a pagar'),
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.Turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensalidades',
            name='valordaparcela',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor da parcela'),
        ),
    ]
