# Generated by Django 2.1.7 on 2019-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProjetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentosLimpezaProjetor')),
            ],
        ),
    ]
