# Generated by Django 2.1.7 on 2019-03-11 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('tecnologiadainformacao', '0001_initial'),
        ('funcionarios', '0004_auto_20190106_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoprojetor',
            name='pertense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tecnologiadainformacao.projetor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pertense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
        ),
    ]
