# Generated by Django 2.1.7 on 2019-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20190319_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pertense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
        ),
        migrations.AlterField(
            model_name='documentoaluno',
            name='pertense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aluno.Aluno'),
        ),
    ]
