# Generated by Django 2.1.7 on 2019-03-11 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoriacursos', '0001_initial'),
        ('aluno', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('duracao', models.IntegerField(blank=True, verbose_name='Duração (Messes)')),
                ('qntalunosminimo', models.IntegerField(blank=True, verbose_name='qnt Alunos Max')),
                ('qntalunosmax', models.IntegerField(blank=True, verbose_name='qnt Alunos Min')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('desconto', models.IntegerField(blank=True, verbose_name='Desconto')),
                ('parcelamento', models.IntegerField(blank=True, verbose_name='Parcelamento')),
                ('idademinima', models.IntegerField(blank=True, verbose_name='Idade Mínima')),
                ('idademaxima', models.IntegerField(blank=True, verbose_name='Idade Máxima')),
                ('materiais', models.TextField(blank=True, verbose_name='Meteriais')),
                ('Professor', models.TextField(blank=True, verbose_name='Meteriais')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('datamodificacao', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoriacursos.CategoriaCursos', verbose_name='Categorias')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-datacriacao'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('totalapagar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a Pagar')),
                ('desconto', models.IntegerField(blank=True, verbose_name='Desconto')),
                ('parcelamento', models.IntegerField(blank=True, verbose_name='Parcelamento X Vezes ')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('CURSANDO', 'Cursando'), ('AGUARDANDO', 'Aguardando'), ('TRANCADA', 'Trancada')], default='AGUARDANDO', max_length=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('nomeAluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Aluno', to='aluno.Aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'ordering': ['nomeAluno'],
            },
        ),
        migrations.CreateModel(
            name='SalaDeAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome ou número da sala')),
                ('qntalunosmax', models.IntegerField(blank=True, null=True, verbose_name='Idade Máxima de alunos')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'SalaDeAula',
                'verbose_name_plural': 'SalaDeAulas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.TextField(blank=True, verbose_name='Meteriais')),
                ('datainicio', models.DateTimeField(verbose_name='Data Início')),
                ('datafim', models.DateTimeField(verbose_name='Data FIM')),
                ('diadasemana', models.CharField(choices=[(' ---- ', ' ---- '), ('SEGUNDA', 'Segunda'), ('TERÇA', 'Terça'), ('QUARTA', 'Quarta'), ('QUINTA', 'Quinta'), ('SEXTA', 'Sexta'), ('SÁBADO', 'Sábado')], default='----', max_length=9)),
                ('status', models.CharField(choices=[('INICIADA', 'Iniciada'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADA', 'Finalizada')], default='AGUARDANDO', max_length=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('turmadocurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Curso', to='secretaria.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'turmadocurso',
                'verbose_name_plural': 'turmadocurso',
                'ordering': ['turmadocurso'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Turma', to='secretaria.Turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.SalaDeAula'),
        ),
    ]
