# Generated by Django 2.1.7 on 2019-03-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='Professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professores.Professor', verbose_name='Professores'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Professor', to='professores.Professor', verbose_name='Professor'),
        ),
    ]
