# Generated by Django 2.1.7 on 2019-03-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_auto_20190311_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='Professor',
        ),
    ]
