# Generated by Django 2.1.7 on 2019-04-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_remove_curso_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.SalaDeAula'),
            preserve_default=False,
        ),
    ]
