# Generated by Django 2.1.7 on 2019-04-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_turma_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
