# Generated by Django 2.1.7 on 2019-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_matricula_varlorparcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('CURSANDO', 'Cursando'), ('AGUARDANDO', 'Aguardando'), ('TRANCADA', 'Trancada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
