# Generated by Django 2.1.7 on 2019-02-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(max_length=100, verbose_name='TAG')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('datamodificacao', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
    ]
